### ISSUE TITLE
null emoji sometimes

### ISSUE THREAD

**Issue by Everkers** [Everkers/Gremilin-b#1]
sometimes the bot send the emoj champion as null for some unknown reasons 
![image](https://user-images.githubusercontent.com/44750827/71363714-520d0e00-259a-11ea-8ec5-888e250ce61b.png)

**Comment by ziadab** [comment]
Wax be5iti ybyen lik champ image ?

**Comment by ziadab** [comment]
wait but l guild ti5edem gir f guild channels
![image](https://user-images.githubusercontent.com/25710949/71376710-ac21c980-25c2-11ea-9715-6b3f950ca159.png)

**Comment by ziadab** [comment]
![Screenshot from 2019-12-24 23-30-57](https://user-images.githubusercontent.com/25710949/71425454-5a9a3d00-269d-11ea-9d29-03cddee90692.png)
Some shit go on ???

**Comment by ziadab** [comment]
![Screenshot from 2019-12-24 23-57-24](https://user-images.githubusercontent.com/25710949/71425737-c8943380-26a0-11ea-8bfe-2b690e994bb9.png)
Solved wa laye3etik ster la ma kola class dirha bo7edha f file bo7edo Baliz BAAAAAAAAAAAALIZ
and ra handir branch 5era bax txof dakxi nta ki dayr and mazal 5seni nfhem bax ndir delete l emoji mn be3ed
